pipeline {
    stages {
        stage('Build') {
            steps {            
                checkout scm
                echo "OK"
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn --version'
            }
            /*
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }*/
        }
        /*
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
           }
        }*/
    }
}
